---
- name: sudo | Add admin group to sudo
  ansible.builtin.template:
    src: sudoers.j2
    dest: "{{ sssd_ad_sudo_conf_d }}/sssd_ad"
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: "0440"
